<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>model_finetuning</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.4" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Azure.ResourceManager.CognitiveServices" Version="1.5.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="data\dnd_npc_data_train.jsonl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>data\dnd_npc_data_train.jsonl</Link>
    </Content>
    <Content Include="data\dnd_npc_data_valid.jsonl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>data\dnd_npc_data_valid.jsonl</Link>
    </Content>
  </ItemGroup>

</Project>
